DROP TABLE IF EXISTS `gw2_objectives`;
CREATE TABLE IF NOT EXISTS `gw2_objectives` (
  `objective_id` smallint(3) unsigned NOT NULL,
  `score` smallint(2) unsigned NOT NULL,
  `map` varchar(5) NOT NULL,
  `type` varchar(6) NOT NULL,
  `name_de` varchar(40) NOT NULL,
  `name_en` varchar(40) NOT NULL,
  `name_es` varchar(40) NOT NULL,
  `name_fr` varchar(40) NOT NULL,
  PRIMARY KEY (`objective_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `gw2_objectives` (`objective_id`, `score`, `map`, `type`, `name_de`, `name_en`, `name_es`, `name_fr`) VALUES
(1, 25, 'eb', 'keep', 'Aussichtspunkt', 'Overlook', 'Mirador', 'Belvédère'),
(2, 25, 'eb', 'keep', 'Tal', 'Valley', 'Valle', 'Vallée'),
(3, 25, 'eb', 'keep', 'Tiefland', 'Lowlands', 'Vega', 'Basses terres'),
(4, 5, 'eb', 'camp', 'Golanta-Lichtung', 'Golanta Clearing', 'Claro Golanta', 'Clairière de Golanta'),
(5, 5, 'eb', 'camp', 'Pangloss-Anhöhe', 'Pangloss Rise', 'Colina Pangloss', 'Montée de Pangloss'),
(6, 5, 'eb', 'camp', 'Speldan Kahlschlag', 'Speldan Clearcut', 'Claro Espeldia', 'Forêt rasée de Speldan'),
(7, 5, 'eb', 'camp', 'Danelon-Passage', 'Danelon Passage', 'Pasaje Danelon', 'Passage Danelon'),
(8, 5, 'eb', 'camp', 'Umberlichtung-Forst', 'Umberglade Woods', 'Bosques Clarosombra', 'Bois d''Ombreclair'),
(9, 35, 'eb', 'castle', 'Schloss Steinnebel', 'Stonemist Castle', 'Castillo Piedraniebla', 'Château Brumepierre'),
(10, 5, 'eb', 'camp', 'Schurkenbruch', 'Rogue''s Quarry', 'Cantera del Pícaro', 'Carrière des voleurs'),
(11, 10, 'eb', 'tower', 'Aldons Vorsprung', 'Aldon''s Ledge', 'Cornisa de Aldon', 'Corniche d''Aldon'),
(12, 10, 'eb', 'tower', 'Wildbachstrecke', 'Wildcreek Run', 'Pista Arroyosalvaje', 'Piste du Ruisseau sauvage'),
(13, 10, 'eb', 'tower', 'Jerrifers Sumpfloch', 'Jerrifer''s Slough', 'Cenagal de Jerrifer', 'Bourbier de Jerrifer'),
(14, 10, 'eb', 'tower', 'Klovan-Senke', 'Klovan Gully', 'Barranco Klovan', 'Petit ravin de Klovan'),
(15, 10, 'eb', 'tower', 'Langor-Schlucht', 'Langor Gulch', 'Barranco Langor', 'Ravin de Langor'),
(16, 10, 'eb', 'tower', 'Quentinsee', 'Quentin Lake', 'Lago Quentin', 'Lac Quentin'),
(17, 10, 'eb', 'tower', 'Mendons Spalt', 'Mendon''s Gap', 'Zanja de Mendon', 'Faille de Mendon'),
(18, 10, 'eb', 'tower', 'Anzalias-Pass', 'Anzalias Pass', 'Paso Anzalias', 'Col d''Anzalias'),
(19, 10, 'eb', 'tower', 'Ogerwacht-Kanal', 'Ogrewatch Cut', 'Tajo de la Guardia del Ogro', 'Percée de Gardogre'),
(20, 10, 'eb', 'tower', 'Veloka-Hang', 'Veloka Slope', 'Pendiente Veloka', 'Flanc de Veloka'),
(21, 10, 'eb', 'tower', 'Durios-Schlucht', 'Durios Gulch', 'Barranco Durios', 'Ravin de Durios'),
(22, 10, 'eb', 'tower', 'Bravost-Abhang', 'Bravost Escarpment', 'Escarpadura Bravost', 'Falaise de Bravost'),
(23, 25, 'blue', 'keep', 'Festung', 'Garrison', 'Fuerte', 'Garnison'),
(24, 5, 'blue', 'camp', 'Landgut des Champions', 'Champion''s demense', 'Dominio del Campeón', 'Fief du champion'),
(25, 10, 'blue', 'tower', 'Rotdornstrauch', 'Redbriar', 'Zarzarroja', 'Bruyerouge'),
(26, 10, 'blue', 'tower', 'Grünsee', 'Greenlake', 'Lagoverde', 'Lac Vert'),
(27, 25, 'blue', 'keep', 'Bucht des Aufstiegs', 'Ascension Bay', 'Bahía de la Ascensión', 'Baie de l''Ascension'),
(28, 10, 'blue', 'tower', 'Horst der Morgendämmerung', 'Dawn''s Eyrie', 'Aguilera del Alba', 'Promontoire de l''aube'),
(29, 5, 'blue', 'camp', 'Der Geisterholm', 'The Spiritholme', 'La Isleta Espiritual', 'L''antre des esprits'),
(30, 10, 'blue', 'tower', 'Wald-Freistatt', 'Woodhaven', 'Refugio Forestal', 'Gentesylve'),
(31, 25, 'blue', 'keep', 'Askalion-Hügel', 'Askalion Hills', 'Colinas Askalion', 'Collines d''Askalion'),
(32, 25, 'red', 'keep', 'Etheron-Hügel', 'Etheron Hills', 'Colinas Etheron', 'Collines d''Etheron'),
(33, 25, 'red', 'keep', 'Traumbucht', 'Dreaming Bay', 'Bahía Onírica', 'Baie des rêves'),
(34, 5, 'red', 'camp', 'Sieger-Hütte', 'Victors''s Lodge', 'Albergue del Vencedor', 'Pavillon du vainqueur'),
(35, 10, 'red', 'tower', 'Grünstrauch', 'Greenbriar', 'Zarzaverde', 'Vertebranche'),
(36, 10, 'red', 'tower', 'Blausee', 'Bluelake', 'Lagoazul', 'Lac bleu'),
(37, 25, 'red', 'keep', 'Festung', 'Garrison', 'Fuerte', 'Garnison'),
(38, 10, 'red', 'tower', 'Weitsicht', 'Longview', 'Vistaluenga', 'Longuevue'),
(39, 5, 'red', 'camp', 'Das Gottschwert', 'The Godsword', 'La Hoja Divina', 'L''Epée divine'),
(40, 10, 'red', 'tower', 'Felswand', 'Cliffside', 'Despeñadero', 'Flanc de falaise'),
(41, 25, 'green', 'keep', 'Shadaran-Hügel', 'Shadaran Hills', 'Colinas Shadaran', 'Collines de Shadaran'),
(42, 10, 'green', 'tower', 'Rotsee', 'Redlake', 'Lagorrojo', 'Rougelac'),
(43, 5, 'green', 'camp', 'Hütte des Helden', 'Hero''s Lodge', 'Albergue del Héroe', 'Pavillon du Héros'),
(44, 25, 'green', 'keep', 'Schreckensfall-Bucht', 'Dreadfall Bay', 'Bahía Salto Aciago', 'Baie du Noir déclin'),
(45, 10, 'green', 'tower', 'Blaudornstrauch', 'Bluebriar', 'Zarzazul', 'Bruyazur'),
(46, 25, 'green', 'keep', 'Festung', 'Garrison', 'Fuerte', 'Garnison'),
(47, 10, 'green', 'tower', 'Sonnenlichthügel', 'Sunnyhill', 'Colina Soleada', 'Colline ensoleillée'),
(48, 5, 'green', 'camp', 'Glaubenssprung', 'Faithleap', 'Salto de Fe', 'Ferveur'),
(49, 5, 'green', 'camp', 'Blautal-Zuflucht', 'Bluevale Refuge', 'Refugio Valleazul', 'Refuge de bleubal'),
(50, 5, 'red', 'camp', 'Blauwasser-Tiefland', 'Bluewater Lowlands', 'Tierras Bajas de Aguazul', 'Basses terres d''Eau-Azur'),
(51, 5, 'red', 'camp', 'Astralholm', 'Astralholme', 'Isleta Astral', 'Astralholme'),
(52, 5, 'red', 'camp', 'Arahs Hoffnung', 'Arah''s Hope', 'Esperanza de Arah', 'Espoir d''Arah'),
(53, 5, 'red', 'camp', 'Grüntal-Zuflucht', 'Greenvale Refuge', 'Refugio de Valleverde', 'Refuge de Valvert'),
(54, 5, 'green', 'camp', 'Nebel-Freistatt', 'Foghaven', 'Refugio Neblinoso', 'Havre gris'),
(55, 5, 'green', 'camp', 'Rotwasser-Tiefland', 'Redwater Lowlands', 'Tierras Bajas de Aguarroja', 'Basses terres de Rubicon'),
(56, 5, 'green', 'camp', 'Die Titanenpranke', 'The Titanpaw', 'La Garra del Titán', 'Bras du titan'),
(57, 10, 'green', 'tower', 'Felsenspitze', 'Cragtop', 'Cumbrepeñasco', 'Sommet de l''escarpement'),
(58, 5, 'blue', 'camp', 'Götterkunde', 'Godslore', 'Sabiduría de los Dioses', 'Divination'),
(59, 5, 'blue', 'camp', 'Rottal-Zuflucht', 'Redvale Refuge', 'Refugio Vallerojo', 'Refuge de Valrouge'),
(60, 5, 'blue', 'camp', 'Sternenhain', 'Stargrove', 'Arboleda de las Estrellas', 'Bosquet stellaire'),
(61, 5, 'blue', 'camp', 'Grünwasser-Tiefland', 'Greenwater Lowlands', 'Tierras Bajas de Aguaverde', 'Basses terres d''Eau-Verdoyante');